# vim ft=yaml
# CI on Windows via appveyor
# Largely from:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - set PYTHON="C:\\Python27"
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Fix MSVC builds for 64-bit Python
  # See
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - python -m pip install --upgrade pip

build_script:
  # - pip install --no-index -f %MWPY_URL% numpy
  - pip install numpy

test_script:
  # Run the project tests
  # - python -c "import numpy; numpy.test(verbose=3)"
  # Does msys bork the tests?
  - PATH=%PATH%;c:\msys64\usr\bin
  - pip install nose
  - python -c "import numpy"
  - set PY_CMD=python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"
  - for /f "tokens=1 delims=" %%i in ('%PY_CMD%') do set NUMPY_DIR=%%i
  - nosetests --verbosity=5 %NUMPY_DIR%\distutils\tests %NUMPY_DIR%\f2py\tests
